const cartItems = [
  {
    id: 1,
    title: "Smartphone X1",
    price: 799.99,
    image: "https://via.placeholder.com/150?text=Smartphone+X1",
    img: "Smartphone X1 image",
    amount: 1,
  },
  {
    id: 2,
    title: "Laptop Pro 15",
    price: 1299.99,
    image: "https://via.placeholder.com/150?text=Laptop+Pro+15",
    img: "Laptop Pro 15 image",
    amount: 1,
  },
  {
    id: 3,
    title: "Wireless Headphones",
    price: 199.99,
    image: "https://via.placeholder.com/150?text=Wireless+Headphones",
    img: "Wireless Headphones image",
    amount: 1,
  },
  {
    id: 4,
    title: "Smartwatch 3",
    price: 249.99,
    image: "https://via.placeholder.com/150?text=Smartwatch+3",
    img: "Smartwatch 3 image",
    amount: 1,
  },
  {
    id: 5,
    title: "Tablet S8",
    price: 399.99,
    image: "https://via.placeholder.com/150?text=Tablet+S8",
    img: "Tablet S8 image",
    amount: 1,
  },
  {
    id: 6,
    title: "Bluetooth Speaker",
    price: 89.99,
    image: "https://via.placeholder.com/150?text=Bluetooth+Speaker",
    img: "Bluetooth Speaker image",
    amount: 1,
  },
  {
    id: 7,
    title: "4K TV 55\"",
    price: 649.99,
    image: "https://via.placeholder.com/150?text=4K+TV+55%22",
    img: "4K TV 55-inch image",
    amount: 1,
  },
  {
    id: 8,
    title: "Gaming Console X100",
    price: 499.99,
    image: "https://via.placeholder.com/150?text=Gaming+Console+X100",
    img: "Gaming Console X100 image",
    amount: 1,
  },
  {
    id: 9,
    title: "Smart Bulbs (Pack of 2)",
    price: 39.99,
    image: "https://via.placeholder.com/150?text=Smart+Bulbs",
    img: "Smart Bulbs Pack image",
    amount: 1,
  },
  {
    id: 10,
    title: "Electric Scooter",
    price: 399.99,
    image: "https://via.placeholder.com/150?text=Electric+Scooter",
    img: "Electric Scooter image",
    amount: 1,
  },
  {
    id: 11,
    title: "Instant Camera",
    price: 129.99,
    image: "https://via.placeholder.com/150?text=Instant+Camera",
    img: "Instant Camera image",
    amount: 1,
  },
  {
    id: 12,
    title: "VR Headset Pro",
    price: 299.99,
    image: "https://via.placeholder.com/150?text=VR+Headset+Pro",
    img: "VR Headset Pro image",
    amount: 1,
  },
  {
    id: 13,
    title: "Portable Power Bank",
    price: 29.99,
    image: "https://via.placeholder.com/150?text=Portable+Power+Bank",
    img: "Portable Power Bank image",
    amount: 1,
  },
  {
    id: 14,
    title: "Drone X300",
    price: 799.99,
    image: "https://via.placeholder.com/150?text=Drone+X300",
    img: "Drone X300 image",
    amount: 1,
  },
];

export default cartItems;
